"""Train vs val vs test at a MATCHED decode, with user-clustered CI bands.

Sibling of plot_train_val_test.py, not a replacement. That figure plots the
in-training train/val curves, where train is sampled at the training temperature
(1.0, 4 rollouts per prompt) and has no step-0 point. Those two facts are stated
in its subtitle and are exactly what this figure removes: here all three splits
are generated by the same offline pipeline at the same decode (temp 0.7 /
top_p 0.8 / top_k 20, one sample per prompt) and judged by the same Qwen3.5-9B
cell, so a gap between the curves is a property of the SPLIT, not of the sampler.

The bands are +/- 1.96 user-clustered SE. They are the point of the figure: the
splits have very different user counts (train 636, val 349, test 128 users) and
test's rows cluster ~6.9 to a user, so equal-looking gaps carry unequal evidence.
Drawing the curves bare invites reading a sub-noise separation as real.

Input (under --eval_root):
  split_curves.csv   scripts/compare_split_curves.py

Usage:
  python scripts/plot_split_curves.py \
      --eval_root results/2026-08-06-train-val-eval-9b-half
"""
from __future__ import annotations

import argparse
import csv
from collections import defaultdict
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402

from plotstyle import INK, SLOT, apply_rc, declutter, style_axes  # noqa: E402

# Same slot-by-entity assignment as plot_train_val_test.py so the two figures
# cannot disagree about which colour means which split.
SPLITS = [
    ("train", "Train", SLOT[1]),
    ("val", "Val", SLOT[3]),
    ("test", "Test", SLOT[2]),   # drawn last: the held-out reference sits on top
]

PANELS = [
    ("likert_mean", "likert_se_clustered", "Mean judge rating", "Likert 1-7", 4.0,
     "4 = cannot tell"),
    ("win_rate_ge5", "win_rate_se_clustered", "Generator win rate",
     "fraction rated >= 5", 0.5, "0.5 = parity"),
]


def read_curves(path: Path) -> dict[str, list[dict]]:
    data: dict[str, list[dict]] = defaultdict(list)
    with path.open() as fh:
        for row in csv.DictReader(fh):
            rec = {"step": int(row["step"]), "n": int(row["n"]),
                   "n_users": int(row["n_users"])}
            for k in ("likert_mean", "likert_se_clustered", "win_rate_ge5",
                      "win_rate_se_clustered"):
                rec[k] = float(row[k])
            data[row["arm"]].append(rec)
    for arm in data:
        data[arm].sort(key=lambda r: r["step"])
    return dict(data)


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--eval_root", required=True)
    ap.add_argument("--out_dir", default=None, help="defaults to --eval_root")
    ap.add_argument("--stem", default="split_curves_9b")
    a = ap.parse_args()

    root = Path(a.eval_root)
    out_dir = Path(a.out_dir) if a.out_dir else root
    out_dir.mkdir(parents=True, exist_ok=True)

    src = root / "split_curves.csv"
    if not src.exists():
        raise SystemExit(f"FAIL: missing {src} -- produce it with scripts/compare_split_curves.py")
    data = read_curves(src)

    missing = [k for k, _, _ in SPLITS if k not in data]
    if missing:
        raise SystemExit(f"FAIL: {src} has no rows for {missing}")

    # Every arm must cover the same steps. A short arm would render as a curve
    # that simply stops, which reads as a plateau rather than as missing data.
    step_sets = {k: [r["step"] for r in data[k]] for k, _, _ in SPLITS}
    steps = step_sets["test"]
    for k, got in step_sets.items():
        if got != steps:
            raise SystemExit(f"FAIL: {k} covers {got} but test covers {steps}; "
                             "the curves would not be comparable")

    apply_rc()
    fig, axes = plt.subplots(1, 2, figsize=(11.2, 4.6))

    for ax, (field, se_field, title, ylab, ref, ref_note) in zip(axes, PANELS):
        ax.axhline(ref, color=INK["muted"], lw=1, ls=(0, (4, 3)), zorder=1)

        ends = []
        for key, label, color in SPLITS:
            xs = [r["step"] for r in data[key]]
            ys = [r[field] for r in data[key]]
            los = [r[field] - 1.96 * r[se_field] for r in data[key]]
            his = [r[field] + 1.96 * r[se_field] for r in data[key]]
            ax.fill_between(xs, los, his, color=color, alpha=0.13, lw=0, zorder=2)
            ax.plot(xs, ys, color=color, lw=1.9, ls=(0, (5, 2)), zorder=3, label=label)
            ax.plot(xs, ys, "o", color=color, ms=5.5, zorder=4)
            ends.append((ys[-1], label, color))

        lo, hi = ax.get_ylim()
        fracs = declutter([(y - lo) / (hi - lo) for y, _, _ in ends])
        for (y, label, _), frac in zip(ends, fracs):
            ax.annotate(label, xy=(steps[-1] + 1.2, lo + frac * (hi - lo)),
                        color=INK["primary"], fontsize=10.5, fontweight="bold",
                        va="center", annotation_clip=False)
        ax.annotate(ref_note, xy=(steps[-1] * 0.62, ref), xytext=(0, 5),
                    textcoords="offset points", color=INK["muted"], fontsize=9)
        ax.set_xlim(steps[0] - 1.5, steps[-1] + 6.5)
        style_axes(ax, title, "GRPO step", ylab, steps)

    ns = {k: data[k][-1]["n"] for k, _, _ in SPLITS}
    us = {k: data[k][-1]["n_users"] for k, _, _ in SPLITS}
    fig.suptitle("9B GRPO generator: train vs val vs test at a matched decode, judged by Qwen3.5-9B",
                 color=INK["primary"], fontsize=14.5, fontweight="bold", x=0.008, ha="left", y=1.005)
    fig.text(0.008, 0.918,
             f"Per point: {ns['train']} train rows / {us['train']} users, "
             f"{ns['val']} val / {us['val']}, {ns['test']} test / {us['test']}. "
             "Bands are +/- 1.96 user-clustered SE.",
             color=INK["secondary"], fontsize=10.5, ha="left")
    fig.text(0.008, 0.862,
             "All three splits generated by the same offline pipeline at temp 0.7 / top_p 0.8 / "
             "top_k 20, one sample per prompt.",
             color=INK["secondary"], fontsize=10.5, ha="left")

    handles, labels = axes[0].get_legend_handles_labels()
    leg = fig.legend(handles, labels, loc="lower center", ncol=3, frameon=False,
                     bbox_to_anchor=(0.5, -0.005), fontsize=10.5)
    for text in leg.get_texts():
        text.set_color(INK["secondary"])

    fig.tight_layout(rect=(0, 0.045, 1, 0.838))
    for ext in ("png", "pdf"):
        out = out_dir / f"{a.stem}.{ext}"
        fig.savefig(out, dpi=200 if ext == "png" else None, bbox_inches="tight")
        print(f"wrote {out}")


if __name__ == "__main__":
    main()
